export { archivosAdjuntos } from './archivosAdjuntos';
export { antecedentes } from './atecedentes';
export { atencionAmendments } from './atencionAmendments';
export { atencionAntecedentes } from './atencionAntecedentes';
export { atencionDiagnosticos } from './atencionDiagnosticos';
export { atenciones } from './atenciones';
export { atencionTratamientos } from './atencionTratamientos';
export { auditLog } from './auditLog';
export { centrosMedicos } from './centrosMedicos';
export { derivaciones } from './derivaciones';
export { diagnostico } from './diagnostico';
export { doctoresPacientes } from './doctoresPacientes';
export { fichaPaciente } from './fichaPaciente';
export { historiaClinica } from './historiaClinica';
export { licenciasProfesional } from './licencias';
export { medicamento } from './medicamento';
export { motivosIniciales } from './motivoInicial';
export { notasMedicas } from './notasMedicas';
export { pacienteProfesional } from './pacienteProfesional';
export { pacientes } from './pacientes';
export { pagos } from './pagos';
export { preferenciaPerfilUser } from './preferenciaPerfilUser';
export { recepcionistaProfesional } from './recepcionistaProfesional';
export { recetaMedica } from './recetaMedica';
export { salaDeEspera } from './salaDeEspera';
export { sessions } from './sessions';
export { signosVitales } from './signosVitales';
export { tratamiento } from './tratamiento';
export { turnos } from './turnos';
export { users } from './users';
export { usersCentrosMedicos } from './usersCentrosMedicos';

export { pagosSuscripciones } from './pagosSuscripciones';
export { planes } from './planes';
export { suscripciones } from './suscripciones';

export { aiCredentials } from './aiCredentials';
export { whatsappConversaciones, whatsappMensajes } from './whatsappConversaciones';
export { whatsappSessions } from './whatsappSessions';
export { whatsappSolicitudes } from './whatsappSolicitudes';

