// data/medicamentos-iniciales.ts
export const medicamentosIniciales = [
  {
    id: 'amox-500',
    nombreComercial: 'Amoxicilina',
    nombreGenerico: 'Amoxicilina',
    principiosActivos: ['Amoxicilina'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '500 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIBIOTICO',
  },
  {
    id: 'amox-250',
    nombreComercial: 'Amoxicilina',
    nombreGenerico: 'Amoxicilina',
    principiosActivos: ['Amoxicilina'],
    formaFarmaceutica: 'SUSPENSION',
    concentracion: '250 mg/5 ml',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIBIOTICO',
  },
  {
    id: 'augmentine-875',
    nombreComercial: 'Augmentine',
    nombreGenerico: 'Amoxicilina/Ácido Clavulánico',
    principiosActivos: ['Amoxicilina', 'Ácido Clavulánico'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '875 mg/125 mg',
    laboratorio: 'GSK',
    requiereReceta: true,
    categoria: 'ANTIBIOTICO',
  },
  {
    id: 'ibu-400',
    nombreComercial: 'Ibuprofeno',
    nombreGenerico: 'Ibuprofeno',
    principiosActivos: ['Ibuprofeno'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '400 mg',
    laboratorio: 'Genérico',
    requiereReceta: false,
    categoria: 'ANALGESICO',
  },
  {
    id: 'ibu-600',
    nombreComercial: 'Ibuprofeno',
    nombreGenerico: 'Ibuprofeno',
    principiosActivos: ['Ibuprofeno'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '600 mg',
    laboratorio: 'Genérico',
    requiereReceta: false,
    categoria: 'ANALGESICO',
  },
  {
    id: 'paracet-500',
    nombreComercial: 'Paracetamol',
    nombreGenerico: 'Paracetamol',
    principiosActivos: ['Paracetamol'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '500 mg',
    laboratorio: 'Genérico',
    requiereReceta: false,
    categoria: 'ANALGESICO',
  },
  {
    id: 'para-susp',
    nombreComercial: 'Paracetamol',
    nombreGenerico: 'Paracetamol',
    principiosActivos: ['Paracetamol'],
    formaFarmaceutica: 'JARABE',
    concentracion: '100 mg/ml',
    laboratorio: 'Genérico',
    requiereReceta: false,
    categoria: 'ANALGESICO',
  },
  {
    id: 'omeprazol-20',
    nombreComercial: 'Omeprazol',
    nombreGenerico: 'Omeprazol',
    principiosActivos: ['Omeprazol'],
    formaFarmaceutica: 'CAPSULA',
    concentracion: '20 mg',
    laboratorio: 'Genérico',
    requiereReceta: false,
    categoria: 'GASTROINTESTINAL',
  },
  {
    id: 'losartan-50',
    nombreComercial: 'Losartán',
    nombreGenerico: 'Losartán Potásico',
    principiosActivos: ['Losartán'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '50 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIHIPERTENSIVO',
  },
  {
    id: 'enalapril-10',
    nombreComercial: 'Enalapril',
    nombreGenerico: 'Enalapril Maleato',
    principiosActivos: ['Enalapril'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '10 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIHIPERTENSIVO',
  },
  {
    id: 'atorva-20',
    nombreComercial: 'Atorvastatina',
    nombreGenerico: 'Atorvastatina Cálcica',
    principiosActivos: ['Atorvastatina'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '20 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'HIPOLIPEMIANTE',
  },
  {
    id: 'metformina-850',
    nombreComercial: 'Metformina',
    nombreGenerico: 'Metformina Clorhidrato',
    principiosActivos: ['Metformina'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '850 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIDIABETICO',
  },
  {
    id: 'salbut-inhal',
    nombreComercial: 'Salbutamol',
    nombreGenerico: 'Salbutamol Sulfato',
    principiosActivos: ['Salbutamol'],
    formaFarmaceutica: 'INHALADOR',
    concentracion: '100 mcg/dosis',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'BRONCODILATADOR',
  },
  {
    id: 'fluticasona-inhal',
    nombreComercial: 'Fluticasona',
    nombreGenerico: 'Fluticasona Propionato',
    principiosActivos: ['Fluticasona'],
    formaFarmaceutica: 'INHALADOR',
    concentracion: '125 mcg/dosis',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'CORTICOIDE',
  },
  {
    id: 'loratadina-10',
    nombreComercial: 'Loratadina',
    nombreGenerico: 'Loratadina',
    principiosActivos: ['Loratadina'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '10 mg',
    laboratorio: 'Genérico',
    requiereReceta: false,
    categoria: 'ANTIHISTAMINICO',
  },
  {
    id: 'dexametasona-4',
    nombreComercial: 'Dexametasona',
    nombreGenerico: 'Dexametasona',
    principiosActivos: ['Dexametasona'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '4 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'CORTICOIDE',
  },
  {
    id: 'cipro-500',
    nombreComercial: 'Ciprofloxacina',
    nombreGenerico: 'Ciprofloxacina Clorhidrato',
    principiosActivos: ['Ciprofloxacina'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '500 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIBIOTICO',
  },
  {
    id: 'azitromicina-500',
    nombreComercial: 'Azitromicina',
    nombreGenerico: 'Azitromicina Dihidrato',
    principiosActivos: ['Azitromicina'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '500 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIBIOTICO',
  },
  {
    id: 'clona-0.5',
    nombreComercial: 'Clonazepam',
    nombreGenerico: 'Clonazepam',
    principiosActivos: ['Clonazepam'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '0.5 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'PSICOFARMACO',
  },
  {
    id: 'sertralina-50',
    nombreComercial: 'Sertralina',
    nombreGenerico: 'Sertralina Clorhidrato',
    principiosActivos: ['Sertralina'],
    formaFarmaceutica: 'COMPRIMIDO',
    concentracion: '50 mg',
    laboratorio: 'Genérico',
    requiereReceta: true,
    categoria: 'ANTIDEPRESIVO',
  },
  // ... puedo agregar más según necesites
];
